runtime: python311

entrypoint: uvicorn server:app --host 0.0.0.0 --port $PORT

handlers:
  - url: /.*
    script: auto

env_variables:
  MONGO_URL: "mongodb+srv://fawwazexcel2000_db_user:M2GKHQhCP9TGcqHw@cluster0.rz3r5xy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DB_NAME: "test_database"
  CORS_ORIGINS: "*"
  JWT_SECRET: "mindmate-jwt-secret-key-change-in-production"
